// <auto-generated />
namespace U2_W3_Homework_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required));
        
        string IMigrationMetadata.Id
        {
            get { return "202301211636078_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
